#!/usr/bin/env python3
"""LNbits first-boot bootstrap.

Runs as an init sidecar to LNbits v1.5.x. Idempotent:
  1. Waits for LNbits to be healthy.
  2. If LNbits is in "first install" state, completes the wizard via API
     using a securely-generated admin password. Saves credentials to
     /lnbits-data/admin.json so the operator can find them later.
  3. Exits 0.

On subsequent boots: first_install returns 403 ("not your first install"),
the script logs that and exits cleanly.

The espresso app uses LNbits's built-in POST /api/v1/account for staff
onboarding, which doesn't require any extension; the legacy User Manager
extension is no longer needed.

Reads:
  - LNBITS_URL (default http://lnbits:5000)
  - admin credentials file at /lnbits-data/admin.json (if present, reuses)

Writes:
  - /lnbits-data/admin.json on first install
"""

from __future__ import annotations

import json
import os
import secrets
import sys
import time
import urllib.error
import urllib.request

LNBITS_URL = os.environ.get("LNBITS_URL", "http://lnbits:5000").rstrip("/")
CREDS_PATH = "/lnbits-data/admin.json"


def log(msg: str) -> None:
    print(f"[lnbits-init] {msg}", flush=True)


def http(method: str, path: str, *, body: dict | None = None,
         token: str | None = None, timeout: float = 10.0) -> tuple[int, dict | str]:
    headers = {"Content-Type": "application/json"}
    if token:
        headers["Authorization"] = f"Bearer {token}"
    data = json.dumps(body).encode() if body is not None else None
    req = urllib.request.Request(
        f"{LNBITS_URL}{path}", data=data, method=method, headers=headers,
    )
    try:
        with urllib.request.urlopen(req, timeout=timeout) as r:
            text = r.read().decode()
            try:
                return r.status, json.loads(text) if text else ""
            except json.JSONDecodeError:
                return r.status, text
    except urllib.error.HTTPError as e:
        text = e.read().decode() if e.fp else ""
        try:
            payload = json.loads(text) if text else {}
        except json.JSONDecodeError:
            payload = text
        return e.code, payload


def wait_for_health(deadline: float = 180) -> None:
    log(f"waiting for LNbits at {LNBITS_URL}/api/v1/health...")
    end = time.time() + deadline
    while time.time() < end:
        try:
            with urllib.request.urlopen(f"{LNBITS_URL}/api/v1/health",
                                         timeout=3) as r:
                if r.status == 200:
                    log("LNbits is healthy")
                    return
        except (urllib.error.URLError, ConnectionError, TimeoutError):
            pass
        time.sleep(2)
    raise SystemExit(f"LNbits never became healthy after {deadline}s")


def do_first_install() -> dict:
    """Complete the wizard with a generated admin password. Idempotent: if
    LNbits says the install was already done (403), just return whatever's
    in the saved credentials file."""
    if os.path.exists(CREDS_PATH):
        log(f"{CREDS_PATH} already exists; reusing")
        with open(CREDS_PATH) as f:
            return json.load(f)

    password = secrets.token_urlsafe(16)
    log("posting PUT /api/v1/auth/first_install...")
    status, body = http(
        "PUT", "/api/v1/auth/first_install",
        body={"username": "admin", "password": password,
              "password_repeat": password},
    )
    if status == 403:
        log("first_install already done (no creds file saved); "
            "extension install will be skipped")
        return {}
    if status >= 400:
        log(f"first_install failed: {status} {body}")
        raise SystemExit(f"first_install error: {body}")

    creds = {"username": "admin", "password": password,
             "lnbits_url": LNBITS_URL,
             "note": "Generated by lnbits-init. Bookmark this URL or "
                     "rotate the password via the LNbits UI."}
    os.makedirs(os.path.dirname(CREDS_PATH), exist_ok=True)
    with open(CREDS_PATH, "w") as f:
        json.dump(creds, f, indent=2)
    os.chmod(CREDS_PATH, 0o600)
    log(f"admin credentials saved to {CREDS_PATH}")
    return creds


def login(username: str, password: str) -> str | None:
    status, body = http(
        "POST", "/api/v1/auth",
        body={"username": username, "password": password},
    )
    if status == 200 and isinstance(body, dict):
        return body.get("access_token")
    log(f"login failed: {status} {body}")
    return None


def list_installed_extensions(token: str) -> list[str]:
    status, body = http("GET", "/api/v1/extension", token=token)
    if status != 200 or not isinstance(body, list):
        return []
    return [e.get("id", "") for e in body if isinstance(e, dict)]


def install_extension(token: str, ext_id: str) -> bool:
    """Install (and enable) an extension by id from the configured manifests.

    LNbits v1.5.x's POST /api/v1/extension wants the resolved archive URL and
    version, not just an ext_id. Fetch /api/v1/extension/all to get the
    manifest, find our extension's latest release, then install with that.
    """
    status, body = http("GET", "/api/v1/extension/all", token=token)
    if status != 200 or not isinstance(body, list):
        log(f"couldn't fetch extension manifest: {status} {body}")
        return False

    target = None
    for ext in body:
        if not isinstance(ext, dict):
            continue
        if ext.get("id") == ext_id:
            target = ext
            break
    if not target:
        log(f"extension '{ext_id}' not found in manifest "
            f"(available: {[e.get('id') for e in body if isinstance(e, dict)][:10]})")
        return False

    # latestRelease describes the archive URL and version compatible with
    # this LNbits version.
    rel = target.get("latestRelease") or {}
    archive = rel.get("archive")
    version = rel.get("version")
    source_repo = rel.get("sourceRepo") or rel.get("source_repo") or "lnbits"
    if not archive or not version:
        log(f"no installable release for '{ext_id}' on this LNbits version "
            f"(latestRelease={rel})")
        return False

    status, body = http(
        "POST", "/api/v1/extension",
        token=token,
        body={
            "ext_id": ext_id,
            "source_repo": source_repo,
            "archive": archive,
            "version": version,
        },
    )
    if status in (200, 201, 202):
        log(f"installed extension '{ext_id}' v{version}")
        return True
    if status == 409:
        log(f"extension '{ext_id}' already installed")
        return True
    log(f"extension install error: {status} {body}")
    return False


def main() -> int:
    wait_for_health()
    do_first_install()
    log("done")
    return 0


if __name__ == "__main__":
    sys.exit(main())
